services:
  postgres:
    image: postgres:16-alpine
    container_name: moneyscope-db
    environment:
      POSTGRES_USER: moneyscope_user
      POSTGRES_PASSWORD: moneyscope_password
      POSTGRES_DB: moneyscope_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - moneyscope-net

  # PostgresAdmin for UI-based managing/debugging in case I don't feel like using DataGrip
  pgadmin:
    image: dpage/pgadmin4
    container_name: moneyscope-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@moneyscope.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - moneyscope-net

volumes:
  postgres_data:

networks:
  moneyscope-net:
    driver: bridge